---
AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  LambdaS3Bucket:
    Type: String
    Default: ''
  CFNCustomProviderZipFileName:
    Type: String
    Default: lambdas/elastic-ip-manager-0.1.6.zip
  OpsGenieKey:
    Type: String

Conditions:
  UsePublicBucket: !Equals
    - !Ref 'LambdaS3Bucket'
    - ''

Resources:
  Policy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
        - Effect: Allow
          Resource: "*"
          Action:
            - ec2:DescribeAddresses
            - ec2:DescribeInstances
            - ec2:AssociateAddress
            - ec2:DisassociateAddress
            - tag:GetTagValues

  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      - !Ref Policy
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: custom-metrics
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - cloudwatch:PutMetricData
                Resource: "*"


  Function:
    Type: AWS::Lambda::Function
    Properties:
      Description: Elastic IP manager for Autoscaling Group instances
      FunctionName: elastic-ip-manager
      Code:
        S3Bucket: !If
          - UsePublicBucket
          - !Sub 'binxio-public-${AWS::Region}'
          - !Ref 'LambdaS3Bucket'
        S3Key: !Ref 'CFNCustomProviderZipFileName'
      Handler: elastic_ip_manager.handler
      Role: !GetAtt LambdaRole.Arn
      Runtime: python3.7
      Timeout: 600

  Permission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: "lambda:InvokeFunction"
      FunctionName: !GetAtt Function.Arn
      Principal: events.amazonaws.com

  Sync:
    Type: AWS::Events::Rule
    Properties:
      Description: elastic-ip-manager sync
      ScheduleExpression: rate(5 minutes)
      State: ENABLED
      Targets:
        - Id: elastic-ip-manager
          Arn: !GetAtt Function.Arn

  Trigger:
    Type: AWS::Events::Rule
    Properties:
      State: ENABLED
      EventPattern: |
        {
          "source": [
            "aws.ec2"
          ],
          "detail-type": [
            "EC2 Instance State-change Notification"
          ]
        }
      Targets:
        - Id: elastic-ip-manager
          Arn: !GetAtt Function.Arn

  OpsGenieTopic:
    Type: AWS::SNS::Topic
    Properties:
      Subscription:
        - Endpoint: !Sub https://api.opsgenie.com/v1/json/cloudwatch?apiKey=${OpsGenieKey}
          Protocol: https
      TopicName: !Sub ${AWS::StackName}-opsgenie-de

  ## Alarms
  TooFewEipAddressesAvailable:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: |
        Triggered when there is too few free elastic IPs left to allocate in fizz-egent-eip-pool
        oncall:false
      AlarmName: !Sub ${AWS::StackName}-too-few-eip-addresses-left
      OKActions:
        - !Ref OpsGenieTopic
      AlarmActions:
        - !Ref OpsGenieTopic
      Dimensions:
        - Name: EipPoolName
          Value: fizz-agent-eip-pool
      Namespace: S24/FiZZ
      MetricName: Available-EIPs
      Statistic: Sum
      DatapointsToAlarm: 1
      EvaluationPeriods: 1
      ComparisonOperator: LessThanOrEqualToThreshold
      Period: 300
      Threshold: 3
      TreatMissingData: breaching

  LambdaHasErrors:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: |
        Too many invocation errors of the elastic-ip-manager lambda
        oncall:false
      AlarmName: !Sub ${AWS::StackName}-elastic-ip-manager-lambda-errors
      AlarmActions:
        - !Ref OpsGenieTopic
      OKActions:
        - !Ref OpsGenieTopic
      Dimensions:
        - Name: FunctionName
          Value: !Ref Function
      Namespace: AWS/Lambda
      ComparisonOperator: GreaterThanOrEqualToThreshold
      EvaluationPeriods: 1
      MetricName: Errors
      Period: 60
      Statistic: Sum
      Threshold: 1
      TreatMissingData: notBreaching
